/// <reference types="arcgis-js-api" />
import Portal = require("esri/portal/Portal");
import PortalQueryParams = require("esri/portal/PortalQueryParams");
import { Direction, ApplicationBaseConstructorOptions, ApplicationBaseResults, ApplicationBaseSettings, ApplicationConfig } from "./interfaces";
declare class ApplicationBase {
    constructor(options: ApplicationBaseConstructorOptions);
    settings: ApplicationBaseSettings;
    config: ApplicationConfig;
    results: ApplicationBaseResults;
    portal: Portal;
    direction: Direction;
    locale: string;
    units: string;
    queryGroupItems(groupId: string, itemParams: PortalQueryParams, portal?: Portal): IPromise<any>;
    load(): IPromise<ApplicationBase>;
    private _mixinSettingsDefaults(settings);
    private _limitItemSize(items, allowMultiple);
    private _getPropertyArray(property);
    private _getEsriEnvironmentPortalUrl();
    private _getEsriEnvironmentProxyUrl(portalUrl);
    private _getUnits(portal);
    private _queryGroupInfo(groupId, portal);
    private _loadItem(id);
    private _getLocalConfig(appid);
    private _overwriteItemsExtent(responses, applicationItem);
    private _overwriteItemExtent(item, applicationItem);
    private _getDefaultId(id, defaultId);
    private _getLanguageDirection(rtlLocales?);
    private _mixinAllConfigs(params);
    private _setUpCORS(authorizedDomains, webTierSecurity);
    private _setGeometryService(config, portal);
    private _setPortalUrl(portalUrl);
    private _setProxyUrl(proxyUrl);
    private _registerOauthInfos(oauthappid, portalUrl);
    private _getUrlParamValues(urlParams);
    private _urlToObject();
    private _formatUrlParamValue(urlParamValue);
    private _stripStringTags(value);
}
export = ApplicationBase;
